
development:
  adapter: mysql
  database: trivia_development
  username: root
  password: adminpassword
  host: localhost
test:
  adapter: mysql
  database: trivia_test
  username: root
  password: adminpassword
  host: localhost
production:
  adapter: mysql
  database: trivia_production
  username: root
  password: adminpassword
  host: localhost
